# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.TextField(null='true')),
                ('f_sort', models.TextField(null='true')),
                ('f_modify_time', models.DateTimeField(auto_now=True)),
                ('f_post_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tb_menu',
            },
        ),
    ]
